sudo: false
language: scala
scala:
  - 2.12.2

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

install:
  - "nvm install node"
  - "npm install -g elm"
  - "npm install -g elm-test"

before_script:
  - export TZ=Europe/Berlin

script:
  - sbt ++$TRAVIS_SCALA_VERSION ";run-all-tests ;make"
