sudo: false
language: scala
scala:
  - 2.12.2

before_install:
  - "npm install -g elm@0.18.0"

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot


script:
  - sbt ++$TRAVIS_SCALA_VERSION "make"
